name: build all

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y avr-libc binutils-avr gcc-avr unzip wget

      - name: Compile SP36
        run: make sofirn-sp36-t1616

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: hex/*.hex
